### ISSUE TITLE
Open items in new tab

### ISSUE THREAD

**Issue by RayBB** [fuddl/wd#100]
Title says it, I feel like I'm probably missing some obvious way to open the wikidata item in a new tab.
Right now I just copy/paste the id to wikidata but would be nice to have a one click way of doing it.

**Comment by fuddl** [comment]
you are missing a _rather obscure_ way to open the item in a new tab. you can right click the id and then _Open link in a new tab_

![context menu](https://user-images.githubusercontent.com/842548/200810679-0b5c48a0-d0c0-406a-8623-24c0332b463e.png)

**Comment by RayBB** [comment]
😅 wow that's super easy! Because it's not clickable and doesn't look like I link I didn't even consider right clicking on it... Sorry about that and thanks for sharing!

**Comment by fuddl** [comment]
With the latest version of firefox it is not longer possible to open links from the sidebar in a new tab.

**Comment by fuddl** [comment]
Issue will be appearently solved in firefox:
https://bugzilla.mozilla.org/show_bug.cgi?id=1802521

**Comment by fuddl** [comment]
fixed by firefox in version 108
