### ISSUE TITLE
Label being changed instead of ignored

### ISSUE THREAD

**Issue by slweeb** [fuddl/wd#102]
These labels were the same but capitalized different, which usually should just be ignored, but this time it changed it: https://www.wikidata.org/w/index.php?title=Q48264&type=revision&diff=1764642417&oldid=1759971122

Was a couple weeks ago, but somebody recently undid it as I hadn't noticed.

**Comment by fuddl** [comment]
I don't understand how this happened. I tried to recreate the scenario with [sandbox.fandom.com/wiki/WiKiDaTa_sAnDbOx](https://sandbox.fandom.com/wiki/WiKiDaTa_sAnDbOx) and it [caused this edit](https://www.wikidata.org/w/index.php?title=Q4115189&type=revision&diff=1775532601&oldid=1775532292). No alias existed and the label hasn't been changed.

Do you see what is going on?

**Comment by slweeb** [comment]
Honestly I don't understand it either, it seems to have worked fine all other times. Must be a cosmic ray flipping a bit.

**Comment by fuddl** [comment]
If you find a way to reproduce this reopen this ticket 🙂
