### ISSUE TITLE
Youtube channel id resolver

### ISSUE THREAD

**Issue by fuddl** [fuddl/wd#103]

**Comment by fuddl** [comment]
might not longer be nessessary after [YouTube handle](https://m.wikidata.org/wiki/Wikidata:Property_proposal/YouTube_handle) has passed

**Comment by fuddl** [comment]
> youtube handle now has passed btw. but currently the extension detects a youtube url as channel id instead of handle

I can't confirm this. Please send me a url that you expect to resolve to a handle.

**Comment by thibaultmol** [comment]
if you go to https://www.polygon.com/ and use the addon there, try to find statements and click on the  youtube link. you'll see the addon wants to save it as a youtube channel id instead of handle. But that url format doesn't work. because it actually is a handle.

**Comment by fuddl** [comment]
The link you mean would be:
https://www.youtube.com/user/polygon
This url does not **contain** a handle.

The handle url would be:
https://www.youtube.com/@polygon
Which is correctly identified.

The Username url will resolve to a channel ID. I don't know why that is but someone wanted to collect the username as a channel ids. If we don't want this in the future, we'd have to delete [this statement](https://www.wikidata.org/wiki/Property:P2397#P2397$fb4f2542-493d-9e8f-4e2c-cf3819ebb8bc).

**Comment by fuddl** [comment]
I guess that’s solved now
