### ISSUE TITLE
medium urls detected as mastodon addressed

### ISSUE THREAD

**Issue by RayBB** [fuddl/wd#104]
Example: https://medium.com/@n8agrin

<img width="984" alt="image" src="https://user-images.githubusercontent.com/921217/203424072-16b2328f-3fee-4cce-9d7d-6e634ebf0fc7.png">

I'm pretty sure it shouldn't be doing this. And perhaps it wasn't doing this before? But I can't be sure.

**Comment by fuddl** [comment]
Because somebody added this as a mastodon address:
https://www.wikidata.org/w/index.php?title=Q108123100&type=revision&diff=1505417631&oldid=1505417270

The extension now believes that medium.com is a mastodon instance. As soon as this statement is removed it should not longer think this

**Comment by fuddl** [comment]
The issue should be solved now. But I'd like to prevent similar issues in the future. Maybe I can verify if the server actually is a mastodon instance.

**Comment by fuddl** [comment]
http://example.com/@test should not longer be recognised as a mastodon account even though [the wikidata sandbox claims to have an mastodon account on examle.com](https://www.wikidata.org/w/index.php?title=Q4115189&oldid=1778488975#P4033).

@RayBB reopen if the issue still occours. 🙂
