### ISSUE TITLE
Sort dropdowns by last chosen by user

### ISSUE THREAD

**Issue by slweeb** [fuddl/wd#109]
So, if I previously selected "contact page URL", it would be at the top of the list.

<img width="394" alt="Screen Shot 2022-12-08 at 11 52 53 AM" src="https://user-images.githubusercontent.com/91897291/206514241-c96aa735-0f19-440b-8874-a1e6171ee16a.png">

**Comment by fuddl** [comment]
TIL, if the commit message contains `fixes #[ticket id]` → github will automatically close the issue
