### ISSUE TITLE
Anonymous edits occur on Wikidata without warning even when logged into Wikidata in another tab

### ISSUE THREAD

**Issue by davidhicks** [fuddl/wd#11]
Environment:
Firefox v84.0.1 on Linux.
This extension v0.132.
No other extensions enabled.

Steps to reproduce:
1. Close all instances of Firefox and start a new instance (Firefox starts with this extension side bar closed).
2. Login to Wikidata.
3. Open this extension side bar.
4. Open a new tab and navigate to an item on an external site e.g. IMDB.
5. Add a missing external ID to an existing Wikidata object using this extension side bar.
6. Note in Wikidata that the edit was done anonymously with the IP address showing, instead of being made with the Wikidata account logged into under step (2).

Would it be possible to warn users that the edit they're about to make would be done anonymously, and then provide information on what would need to be done to login to Wikidata?

**Comment by derenrich** [comment]
i believe there is an wikibase API flag that prevents an edit if it would be anonymouos

**Comment by fuddl** [comment]
Isn't it generally desirable to allow anonymous edits? But I agree, there should at least be a warning, in case the user doesn't want to share her ip address.

**Comment by davidhicks** [comment]
I can see other people have made edits successfully under their account (not anonymously) with this extension but am interested whether anyone has tried this extension on a recent Linux version of Firefox? Perhaps some newer security features in Firefox are blocking the ability for the extensions to retrieve Wikidata cookie information from Wikidata sessions in other tabs?

**Comment by fuddl** [comment]
@davidhicks I cannot reproduce this error on Firefox 84.0.2 (64-bit) on macOS.

What does your firefox say under permissions for the wikidata app?
![wikidata for firefox permissions](https://user-images.githubusercontent.com/842548/104621017-ed828c80-568f-11eb-9f4d-6d942901a5e7.png)

**Comment by davidhicks** [comment]
I tracked down the problem by cloning this repository and launching with "web-ext run" (default browser state) and confirming it worked in that scenario. It turns out that I had privacy.firstparty.isolate=true set in the other browser session where edits were always being made anonymously. When I changed privacy.firstparty.isolate=false in the "web-ext run" session, that too also failed to make authenticated edits (edits become anonymous).

The fetch API doesn't mention firstPartyDomain or first party isolation but the cookie API does. And the fetch API also doesn't allow for the Cookie headers to be overridden with values obtained via cookie API (specifying firstPartyDomain to obtain the correct cookie). It seems that when you're browsing in a tab with domain "en.wikipedia.org" in the URL bar, firstPartyDomain=en.wikipedia.org so the fetch API will check for cookies with a firstPartyDomain=en.wikipedia.org and domain=wikidata.org when attempting to communicate with wikidata.org. Of course there is no cookie matching this search critieria--only one matching firstPartyDomain=wikidata.org and domain=wikidata.org would exist.

Perhaps the Wikidata extension could, within it's own origin of mozjs:// or whatever it is, authenticate with Wikidata APIs and generate a cookie within the origin of the extension? I'm not sure what else would be possible?

For the timebeing, could the readme be updated to state that for authenticated edits to work, privacy.firstparty.isolate must be set to false?

**Comment by davidhicks** [comment]
The suggestion of the extension checking whether the edit would be authenticated or not only seems to be possible if the extension requested the "cookie" permission and then also used the cookie API (first firstPartyDomain=wikidata.org and domain=wikidata.org) to check the value of the "wikidatawikiUserName" cookie. A statement could be added next to the Save button in the sidebar stating "This edit will be made by user account UserName" or "This edit will be made anonymously revealing your IP address". My question though is the MediaWiki/WikiBase APIs don't seem to have a parameter to block anonymous edits, so would the edit still be accepted (as anonymous) in some situations where the "wikidatawikiUserName" cookie is non-null?

**Comment by derenrich** [comment]
i believe the request can make assertions about the status of the current user using the "assert" or "assertuser" param

See https://www.wikidata.org/wiki/Special:ApiSandbox#action=wbsetclaimvalue&claim=Q42%24D8404CDA-25E4-4334-AF13-A3290BCD9C0F&snaktype=value&value=%7B%22entity-type%22:%22item%22,%22numeric-id%22:1%7D&token=foobar&baserevid=7201010

**Comment by fuddl** [comment]
> For the timebeing, could the readme be updated to state that for authenticated edits to work, `privacy.firstparty.isolate` must be set to `false`?

sure. Please make a pull request 🙂

**Comment by fuddl** [comment]
I think that as long Wikidata does not require a login, this extension shouldn't do either. On the other hand, the user should be informed about what might happen without a login. 

@derenrich @davidhicks what do you think about a warning that anonymous users see, whenever they try to create an edit:

<img width="416" alt="User warning" src="https://user-images.githubusercontent.com/842548/108237069-d24fe480-7147-11eb-8c42-d2ff1aef2d28.png">

**Comment by davidhicks** [comment]
That warning looks good!

As a follow up to to this issue, Firefox 86 is introducing "state partitioning" which appears to be a stronger version of "first party isolation" that prevents this addon being used with a logged in account in Firefox 85 and below. In Firefox 86 a user can turn on "strict" privacy protection in the main settings (easy for users to find/access) and then it looks like they might not be able to use this addon with a logged in account either. See https://hacks.mozilla.org/2021/02/introducing-state-partitioning/ for more on state partitioning.

**Comment by fuddl** [comment]
i have added the error message in `0.146`.

@davidhicks I am using _Firefox 86.0 (64-bit)_ in _Strict_ mode. So far I have not encountered such a problem. It it appears in the future, it should at least be obvious to the user thanks to the message.
