### ISSUE TITLE
Better entity search for Open Library authors

### ISSUE THREAD

**Issue by RayBB** [fuddl/wd#111]
Hello,

When I go to a page like https://openlibrary.org/authors/OL41855A/Bernard_Ireland, the search automatically starts looking for `Bernard Ireland | Open Library`. I assume it's parsing the page title or some other piece of data.

However, if I got to, for example, a random LinkedIn profile, which has a similar title `First Last | LinkedIn` the search correctly just looks for `First Last`.

Any way to fix this?

**Comment by fuddl** [comment]
yes! you can add a [website title extract pattern](https://www.wikidata.org/w/index.php?title=Property%3AP648&type=revision&diff=1789374514&oldid=1781550825). Or you can ask me to do it. Now the extension should be able to properly extract the label from the title.
