### ISSUE TITLE
Looks like the Google Map id is not extracted from Google Map

### ISSUE THREAD

**Issue by salgo60** [fuddl/wd#127]
Example
* [Google Map Köpinge kyrka](https://goo.gl/maps/tpjmhcC8VHKZw8jt8) same as WD [Q10552173](https://www.wikidata.org/wiki/Q10552173) 

Is there an easy way to debug the tool?

**Comment by fuddl** [comment]
should be working now in the latest version in chrome and firefox. 

![google maps on google chrome latest version working](https://github.com/fuddl/wd/assets/842548/524759bf-9547-4bcd-9ed1-ee37c68e5a52)

Can you confirm?

**Comment by salgo60** [comment]
Thanks @fuddl it works - closed

**Question:** I dont understand were you find the Google Map id is it possible from the UI to find it?

**Comment by fuddl** [comment]
> Question: I dont understand were you find the Google Map id is it possible from the UI to find it?

[See here](https://www.wikidata.org/wiki/Wikidata_talk:Tools/Wikidata_for_Web#Google_Maps_issue)
