### ISSUE TITLE
setting `instance of` to `writer` isn't recommended.

### ISSUE THREAD

**Issue by davidscotson** [fuddl/wd#129]
The code will suggest to set `instance of` to `writer` (but needs opted in, it's not automatically ticked) based on an og:type of books.author in the metadata.

Ideally this would an option to set `occupation` to `writer` instead, but I'm not sure if that's a small change or not.

**Comment by fuddl** [comment]
where exactly did you find it?

**Comment by davidscotson** [comment]
I'm thinking that something like this might work

```
	{
		name: 'og:type',
		prop: 'P106',
		type: 'WikibaseItem',
		options: {
			'books.author': 36180,		
		},
		suggested: true,
	},
```

Though not sure without trying it wether repeating the name og:type would cause issues.

**Comment by fuddl** [comment]
I mean, on which website?

**Comment by davidscotson** [comment]
Yep, 5 makes sense. Tested and it's working as expected.

**Comment by fuddl** [comment]
thanks for making me aware of this. I actually forgot about this opengraph class matching 😅

**Comment by fuddl** [comment]
But it would be better if we'd get both:
![](https://github.com/fuddl/wd/assets/842548/07a3ff0f-3fe3-4938-88aa-5a2484b694cd)

**Comment by davidscotson** [comment]
Ah very nice. I actually tried to do this myself, got as far as the changes in the first 8 lines of the diff, but it didn't work, presumably needing the more extensive changes.

I'll do some testing, but this looks great.

**Comment by fuddl** [comment]
@davidscotson should be in the latest firefox version `.318`. let me know if you notice any issues with this. You can just reopen this ticket. 🙂
