### ISSUE TITLE
Sidebar should link to item page when item exists

### ISSUE THREAD

**Issue by Sanqui** [fuddl/wd#133]
Here's an easy one: when I use the sidebar to find out whether a Wikidata item for the current page exists, if it does, I should be able to open it in a new browser tab using a single click.  Ideally, the heading with the item name and Q-id should be a link, similarly to how the properties are.

![image](https://github.com/fuddl/wd/assets/289437/757e1af7-7b2f-44fd-8727-37233f481947)

**Comment by fuddl** [comment]
I know this is a little obscure but you can already do that by right-clickinging the id:
![](https://github.com/fuddl/wd/assets/842548/09911c76-6aa3-4ff5-9be1-1d9b2cf603c2)

**Comment by Sanqui** [comment]
Cheers, that works for me!  I probably tried right-clicking the heading, but not the Q-id.

**Comment by fuddl** [comment]
I'll make a more obvious link

**Comment by fuddl** [comment]
@Sanqui please checkout the latest firefox version

**Comment by fuddl** [comment]
well, I'm happy. reopen if you aint 🙃
