### ISSUE TITLE
Help fix ID extraction from thecoversation.com

### ISSUE THREAD

**Issue by RayBB** [fuddl/wd#134]
Right now urls like https://theconversation.com/profiles/matan-shelomi-1245461 don't get picked up by wikidata for web.

But they should match this property: https://www.wikidata.org/wiki/Property:P8207

Any idea why this doesn't work? I don't recall if it ever worked but I've been using the site more so would like to start connecting it.

Thanks!

**Comment by btcprox** [comment]
I just tweaked the [URL match pattern](https://www.wikidata.org/wiki/Property:P8966) value on that property (which the extension relies on): it originally didn't account for the optional name segment in the URL (in your example, the `matan-shelomi-` bit). The correction should eventually allow the extension to detect and parse the URL correctly.

If you know your way around RegEx, you could potentially fix other ID properties in a similar manner by adjusting their URL match patterns.

**Comment by fuddl** [comment]
@RayBB @btcprox this issue as been solved already. Has it?

**Comment by RayBB** [comment]
It's working! Thanks for the help :)

**Comment by fuddl** [comment]
@RayBB there is an [ongoing thread on my talk pag](https://www.wikidata.org/wiki/Topic:Xga68gakeyd9h50s) that is (I think) also monitored by other people. I might react quicker there. Feel free to use that in the future.
