### ISSUE TITLE
Chrome extension 404?

### ISSUE THREAD

**Issue by RayBB** [fuddl/wd#137]
Is it just me or is the chrome extension missing?
https://chrome.google.com/webstore/detail/wikidata/iijkiilckldlddidhaomggfadfafpdfd

**Comment by fuddl** [comment]
yes, the chrome version is currently unmaintained. I reworked the whole extension over at [wikibase-for-web](https://github.com/fuddl/wikibase-for-web) but it currently online works in Firefox.

**Comment by RayBB** [comment]
Might be worth removing the chrome link and adding a note that it's Firefox
only for now.

Anyway, love the extension and happy it works so well on Firefox!
