### ISSUE TITLE
links (income edges) view links only to links view

### ISSUE THREAD

**Issue by camelCaseNick** [fuddl/wd#14]
The links view for what links to an item is a sink regarding linking between views, e.g., you cannot get back to the entity (outgoing edges) view. Additionally, the links view only links to the links view of the properties and items displayed on it. This can lead to confusion: When a selected item has an incoming link from an item with no incoming links, clicking on this item in the links view results in an empty screen. I would have expected to get to the entity view anytime I click on an entity.

**Comment by fuddl** [comment]
@camelCaseNick thanks for your contributions ❤️
