### ISSUE TITLE
Links on Twitter don't work

### ISSUE THREAD

**Issue by overcast07** [fuddl/wd#21]
I've tried using [Twitter search](https://twitter.com/search?q=discord.com%2Finvite%20filter%3Averified&src=typed_query&f=live) to add Discord invite IDs (P9078) for people with verified Twitter accounts. For example, [this tweet](https://twitter.com/songadaymann/status/1371526490945376257) would be usable as a reference. However, both on the search page and on the page for the tweet itself, I wasn't able to add a P9078 statement to Jonathan Mann (Q6273813).

(Even if I had been able to do this, I would have had to add qualifiers separately to avoid constraint violations.)

**Comment by camelCaseNick** [comment]
There are multiple things to it:
* The current logic for adding external identifiers to Wikidata with Wikidata for Firefox is to open the respective page for the identifier — in this case the Discord invitation link. When on that page, the Wikidata for Firefox sidebar should ask you to find the matching item on Wikidata to _connect to Wikidata_. Though from a user standpoint this suggested workflow makes sense as well.
* If Wikidata for Firefox supported adding additional external identifiers from already connected pages, it still would rely on the pages actually containing those links and not using redirecting URLs, which Twitter does with their t.co shortener. Checking every outgoing link for potential redirects is not feasible, so to change this Twitter-specific code would be required.
* Asking for the by constraint required qualifiers in an additional step only makes sense, when they are always self-explanatory, and I don't think _has quality_ is. Don't external identifiers make sense regardless of missing qualifiers?

**Comment by fuddl** [comment]
Yes, I don't think there is much we can do solely because twitter does not directly link to anything. 🤷
