### ISSUE TITLE
use JavaScript modules

### ISSUE THREAD

**Issue by fuddl** [fuddl/wd#22]
since [bugzilla:1536094](https://bugzilla.mozilla.org/show_bug.cgi?id=1536094) seems to be fixed now, I would like to the whole application to use [native javascript modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules). That would not only make the code easier to read, it also allows us to use third party libraries like https://github.com/maxlath/wikibase-sdk

**Comment by camelCaseNick** [comment]
Does the Add-On Developer Hub have any indications for Firefox versions of the users, to know when v 89 will reach most of them?

**Comment by fuddl** [comment]
Not that I know. But I think there is a way to limit an update to a certain Firefox version in the manifest

**Comment by fuddl** [comment]
Cant say it works in the current nightly. 
![fireflox nightly js modules](https://user-images.githubusercontent.com/842548/114277821-27fc8b00-9a2d-11eb-854a-72396f5eaaa5.png)

I had already prepared the `modules` branch.

**Comment by fuddl** [comment]
I think the fix of [1536094](https://bugzilla.mozilla.org/show_bug.cgi?id=1536094) will be shipped with Firefox 89. Thats how I interpret [it's tracking flags](https://wiki.mozilla.org/Release_Management/Release_Process#tracking-firefoxXX).

**Comment by fuddl** [comment]
![Screen Shot 2021-05-01 at 13 26 42](https://user-images.githubusercontent.com/842548/116781081-eafe4400-aa80-11eb-8dab-e3cf3ab91d72.png)
