### ISSUE TITLE
[BUG] Adding claims multiple times

### ISSUE THREAD

**Issue by CennoxX** [fuddl/wd#32]
Example: https://www.wikidata.org/w/index.php?title=Q110042758&oldid=1541787263
The addon is adding the statement P31:Q21191270 (is a: television series episode) multiple times. The expected behaviour would be to check every time if the statement is already existing, and if so, to add the statement only one time and add the references to the already existing claim.

**Comment by fuddl** [comment]
The thing is: the application already asks the Wikidata SPARQL API if the statement is already present. But Wikidata doesn't know it right away. One solution would be keeping a virtual copy of the entity after every edit or use a more up to date API to request if the statement exist.

**Comment by CennoxX** [comment]
The SPARQL api is not suitable for this purpose. In that case the MediaWiki api should be used instead.

**Comment by fuddl** [comment]
I want this fixed. Thanks for posting

**Comment by fuddl** [comment]
These (P31 statements/P31 references) were created [less then a minute apart](https://www.wikidata.org/w/index.php?title=Q110138312&action=history).

![](https://user-images.githubusercontent.com/842548/146249458-506748d1-87e0-438b-b8a4-1558d1a1eee5.png)

I will ship the change in the latest release and we'll see.

**Comment by CennoxX** [comment]
Works as intended!
