### ISSUE TITLE
[BUG] Adding duration claim with wrong format

### ISSUE THREAD

**Issue by CennoxX** [fuddl/wd#33]
Example: https://www.wikidata.org/w/index.php?title=Q110138137&oldid=1544732821#P2047

The addon adds episode durations accurate to the second, but the duration of an episode should be accurate to the minute. Take a look at the interface of trakt.tv, where the information is from. Even if they save it accurate to the second, the duration is always a round minute.

Expected behaviour: Check whether the duration is divisible by 60, if so, save the minute duration. In combination with https://github.com/fuddl/wd/commit/4806506605383a6b97c2cd02c22e33bdf17005c6 the example above would ideally lead to only one claim with 24 minutes and two references.

**Comment by fuddl** [comment]
the duration is extracted from meta tags such as this 

```html
<meta property="video:duration" content="1440">
```

which [according to the specification](https://ogp.me/#type_video.movie) is:

> The movie's length in seconds.

I wanted to submit data in the form it occurs if possible.

But I agree. I don't think trakt.tv stores stores any duration in seconds, they just convert it to comply with the specification. Let's convert the number:

* to years if it happens to be dividable by `31557600`
* to weeks if it happens to be dividable by `604800`
* to days if it happens to be dividable by `86400`
* to hours if it happens to be dividable by `3600`
* to minutes if it happens to be dividable by `60`

> Expected behaviour: Check whether the duration is divisible by 60, if so, save the minute duration. In combination with https://github.com/fuddl/wd/commit/4806506605383a6b97c2cd02c22e33bdf17005c6 the example above would ideally lead to only one claim with 24 minutes and two references.

The `getExistingStatement` check does not jet cover the `Quantity` type. But I'll make sure it will 😅

**Comment by fuddl** [comment]
@CennoxX please update to `0.210` and close this ticket if it works as expected

**Comment by CennoxX** [comment]
Works as intended!
