### ISSUE TITLE
Add an ability to "go back" within the sidebar

### ISSUE THREAD

**Issue by Stvad** [fuddl/wd#41]
Right now when you click on any link/action in the sidebar there is no way for you to to a previous state, which is frustrating

Having a "back" (and potentially forward) button would be helpful. 

Should be reasonably easy to do with Iframe version (#38) - https://stackoverflow.com/questions/3254985/back-and-forward-buttons-in-an-iframe/43334137

**Comment by fuddl** [comment]
`window.history.back();` should also be possible in the sidebar. I will do this once #34 is merged
