### ISSUE TITLE
outsource regular expressions to wikidata

### ISSUE THREAD

**Issue by fuddl** [fuddl/wd#5]
`resolver__regex.js` currently contains a list of regular expressions the extract `external-id` from urls that contain them:

```yaml
P345:  /^https:\/\/(?:www|m)\.imdb\.com\/(?:(?:search\/)?title(?:\?companies=|\/)|name\/|event\/|news\/)(\w{2}\d{7})/,
P8013: /^https:\/\/trakt\.tv\/(people\/[^\/]+|movies\/[^\/]+|shows\/[^\/]+\/seasons\/\d+\/episodes\/\d+)/,
P2002: /^https:\/\/(?:(?:mobile\.)?twitter\.com\/(?:intent\/user\?screen_name\=)?(?!hashtag)([0-9A-Za-z_]{1,15})|tools\.wmflabs\.org\/scholia\/twitter\/([0-9A-Za-z_]{1,15}))/,
P434:  /^https:\/\/(?:musicbrainz\.org\/artist\/|www\.bbc\.co\.uk\/music\/artists\/)([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/,
P436:  /^https:\/\/musicbrainz\.org\/release-group\/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/,
P724:  /^https:\/\/archive\.org\/details\/([0-9A-Za-z@\._-]+)/,
P2969: /^https:\/\/www\.goodreads\.com\/book\/show\/(\d+)/,
P6327: /^https:\/\/www\.goodreads\.com\/characters\/(\d+)/,
P1651: /^https:\/\/www\.youtube\.com\/watch\?v=([-_0-9A-Za-z]{11})/,
P1821: /^https:\/\/\w+\.openfoodfacts\.org\/category\/((?:[a-z]{2,3}:)?[a-z-]+)/,
P5930: /^https:\/\/\w+\.openfoodfacts\.org\/ingredient\/((?:[a-z]{2,3}:)?[a-z-]+)/,
P2397: /^https:\/\/\w+\.youtube\.com\/channel\/(UC[-_0-9A-Za-z]{21}[AQgw])/,
P4198: /^https:\/\/play\.google\.com\/(?:store\/music\/artist\?id=|music\/listen\#\/(?:wst\/)?artist\/)(([A-Z]|[a-z]|[0-9]){27})/,
P4300: /^https:\/\/(?:music|www)\.youtube\.com\/playlist\?list=((?:PL|OLAK|RDCLAK)[-_0-9A-Za-z]+)/,
P5327: /^https:\/\/www\.fernsehserien\.de\/([^?#]+)/,
P3984: /^https:\/\/www\.reddit\.com\/r\/([^\/?#]+)\//,
P1733: /^https:\/\/(?:store\.)?steam(?:community|powered)\.com\/app\/(\d+)/,
P2725: /^https:\/\/www\.gog\.com\/([^#?]+)/,
P4477: /^https:\/\/www\.humblebundle\.com\/store\/([^#\?\/]+)/,
P1933: /^https:\/\/www\.mobygames\.com\/game\/([^#\?\/]+)/,
```

ideally these regular expressions should be provided by the wikidata community.

* [A property should be proposed](https://www.wikidata.org/w/index.php?action=edit&preload=Wikidata%3AProperty+proposal%2FProposal+preload%2Fen&preloadparams%5B0%5D=generic&editintro=Wikidata%3AProperty+proposal%2FEditintro%2Fen&title=Wikidata%3AProperty+proposal%2FURL+extractor+regular+expression&create=Create+request+page)
* replace the list of regular expressions in `resolver__regex.js` with one queries from wikidata

**Comment by derenrich** [comment]
can't you get this by parsing the formatter? e.g. P1630 and P1793?

**Comment by fuddl** [comment]
I tried that but eventually gave up. It even worked in rare cases. But it was a lot of computation for bad results.

**Comment by derenrich** [comment]
interesting. ok.

unrelatedly is this repo connected to a larger project/effort? I'm working on a similar piece of software and would be interested in sharing thoughts.

**Comment by fuddl** [comment]
[a proposal is running](https://www.wikidata.org/wiki/Wikidata:Property_proposal/URL_extractor_regular_expression)
