### ISSUE TITLE
There is no close button in the inline sidebar in "match suggestion" view

### ISSUE THREAD

**Issue by Stvad** [fuddl/wd#67]
New sidebar implementation is missing the close button

![image](https://user-images.githubusercontent.com/81347/156305414-d149d991-6f6b-47a9-84d6-92c91de446d2.png)

repro: go to any page that does not resolve to an existing entity

**Comment by fuddl** [comment]
now there is ![](https://user-images.githubusercontent.com/842548/181786862-72b7a7ee-ec94-4874-bffa-7c4d4451c03f.png)
