### ISSUE TITLE
Add a reference for imported statements

### ISSUE THREAD

**Issue by derenrich** [fuddl/wd#7]
At minimum the URL of the page and retrieval time should be added. If the statement already exists then instead of duplicating it add this as a new reference.

A more sophisticated approach would be to let the user indicate where on the page the statement is claimed and link to that section direccly

**Comment by derenrich** [comment]
oh sorry you do add a reference. missed that somehow. still would like a link to the exact words but this is fine

**Comment by fuddl** [comment]
I actually link to the surrounding element or closed headline if it has an id.

I've been think about quoting the paragraph that contains the link thought. Could be worth a try

**Comment by derenrich** [comment]
So by linking to "exact words" I was thinking about the new text fragment link functionality i.e. https://web.dev/text-fragments/ though it's not yet supported in FF.

**Comment by fuddl** [comment]
that sure looks interesting and more useful than an id hash. I would try to implement it regardless of if firefox supports displaying it. Also that looks like a feature that could be polyfilled.
