### ISSUE TITLE
This extension causes edit links to disappear

### ISSUE THREAD

**Issue by mpeel** [fuddl/wd#71]
List of steps to reproduce (step by step, including full links if applicable):

1. Load https://en.wikipedia.org/wiki/South_Pole_Telescope
2. Select 'The South Pole region' in the 'Microwave and millimeter-wave observations at the South Pole' section
3. Try to edit that section

What happens?:

* The edit link for the section disappears when you select the text

What should have happened instead?:

* The edit link should still remain visible

I originally reported this at https://phabricator.wikimedia.org/T303108 since I thought it was a MediaWiki issue, but it seems to only happen when using this extension. I'm using extension version 0.224 in Firefox 97.0.1 on Mac OS 12.2.1.

**Comment by fuddl** [comment]
Confirmed. Thanks for your report. I’ll look into it

**Comment by fuddl** [comment]
@mpeel the issue should be fixed in version `.225`

**Comment by mpeel** [comment]
Thanks!
