### ISSUE TITLE
Name extracted from muckrack is wrong

### ISSUE THREAD

**Issue by RayBB** [fuddl/wd#81]
Extension scrapes the name "Muck Rack" instead of the actual journalist's name.

Other than that, this is a pretty awesome extension :)

https://muckrack.com/daviddebolt
<img width="999" alt="image" src="https://user-images.githubusercontent.com/921217/172058407-29133ddf-df33-4533-be4f-2cad29d7f173.png">

**Comment by fuddl** [comment]
Some websites contain structured data about the objects in them. In this case there is no structured data about the person and some data about the website. In this case the website is completely irrelevant for us but we have no way of knowing that 😅

We currenty ignore ony `BreadcrumbList`. Maybe we should also ignore `WebSite`? ping @Stvad

**Comment by fuddl** [comment]
Should be fixed in version `0.232`:

<img width="1310" alt="Screenshot 2022-06-20 at 20 19 50" src="https://user-images.githubusercontent.com/842548/174659164-f22e29be-8342-402f-8f9e-09f82e1ab3df.png">

@RayBB feel free to reopen if not

**Comment by RayBB** [comment]
Working great! Ty for fixing
