### ISSUE TITLE
Extract Twitter user numeric ID from Twitter

### ISSUE THREAD

**Issue by RayBB** [fuddl/wd#82]
https://www.wikidata.org/wiki/Property:P6552

**Comment by RayBB** [comment]
1. I used to think that the userid was very easy to find in the HTML. That doesn't seem to be the case anymore. It seems like it's there in the banner url but that's probably no so reliable.
2. You're right about it being a qualifier. If it's the case that this extension doesn't support adding those then this request doesn't make much sense.

Thanks for the answer and maintaining this 👍

**Comment by fuddl** [comment]
No, I think in general it is a valid request. But as I understand, there [is a bot](https://www.wikidata.org/wiki/User:BorkedBot) that automatically add this as a qualifier among others. If it has no direct advantage to the extension user, I would leave this job to BorkedBot. Reopen this issue if you disagree.

If you have further feedback or feature wishes let me know 🙂
