### ISSUE TITLE
"Notifications" always extracted as page title on Facebook

### ISSUE THREAD

**Issue by teolemon** [fuddl/wd#83]
### What
- "Notifications" always extracted as page title on Facebook
- example (I'm doing French city councils): https://www.facebook.com/villedelevallois/
### Screenshot
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/1689815/174431516-aa8e259a-761b-4a9d-bc5d-fd10b03a5056.png">

**Comment by fuddl** [comment]
weired, it works for me. Is it because I have no account?

![](https://user-images.githubusercontent.com/842548/174440392-49ae2aa1-4dce-4ae1-80f2-8e83141843be.png)

**Comment by fuddl** [comment]
Can’t reproduce
