### ISSUE TITLE
Show status of property in social media search results

### ISSUE THREAD

**Issue by teolemon** [fuddl/wd#85]
### What
- Show status of property in social media search results to focus effort on pages not already linked to Wikidata
- Add a green dot whenever for instance the LinkedIn property is already set
### Screenshot
<img width="838" alt="image" src="https://user-images.githubusercontent.com/1689815/174473037-11e990e9-725a-40e9-aff5-9751809614e7.png">

**Comment by fuddl** [comment]
I assume your use case is this:

1. you are on a website that contains links to sites, that should resolve wikidata
2. you want to check which of these links lack a connection yet, without clicking each of them

is that right?

**Comment by teolemon** [comment]
Exactly 💯

**Comment by fuddl** [comment]
There is no dedicated feature to do precisely that **but** i can offer you a workaround.

1. open the website with a hash parameter like `http://example.com/#wd:Q35127` <img width="1289" alt="Screenshot 2022-06-19 at 16 59 24" src="https://user-images.githubusercontent.com/842548/174487467-9313b4fd-388b-41fb-ac5d-faaad5670853.png">
3. scroll to the bottom of the sidebar an click _add a statement_  <img width="1289" alt="Screenshot 2022-06-19 at 16 59 29" src="https://user-images.githubusercontent.com/842548/174487514-9167cb01-c13d-4b33-8904-79e7971fb5d8.png">
4. wait for it to resolve all the links on the page <img width="1289" alt="Screenshot 2022-06-19 at 16 59 54" src="https://user-images.githubusercontent.com/842548/174487556-6367d5f2-b3f3-496b-bc64-98a13bec1d6a.png">
5. wait for it to resolve all the links on the page. unresolved links should remain unchanged

you can open these in a new tab and match them one by one

**Comment by fuddl** [comment]
@teolemon I assume this workaround doesn't work for you?

I'm afraid permanently resolving every link on a page would significantly reduce the browsers performance it might also put a heavy burden on wikimedia's infrastructure.

**Comment by fuddl** [comment]
I’m closing this for now. Reopen if you feel there is something that can be done
