### ISSUE TITLE
Website resolver usually fails

### ISSUE THREAD

**Issue by fuddl** [fuddl/wd#86]
https://www.saint-ouen.fr/ should resolve to https://www.wikidata.org/wiki/Q208889 but doesn't

from #84

**Comment by fuddl** [comment]
@teolemon in this particular scenario it fails because the [Q208889](https://www.wikidata.org/wiki/Q208889) had the url with http while the website used https 😅
![Screen Shot 2022-06-19 at 17 26 04](https://user-images.githubusercontent.com/842548/174488567-fc1cad57-315c-4d15-9269-fc3a6206ac33.png)

**Comment by teolemon** [comment]
Yes that happens with so many stored urls, probably worthwhile handling it in the code (eg stripping prefixes if it's just for detection ?)

**Comment by teolemon** [comment]
Ah you created an issue for it. Sorry, I should have explicitly pointed it in the other issue

**Comment by teolemon** [comment]
Sorry if I lost you time scratching your head

**Comment by fuddl** [comment]
nah, it's fine 🤷

the query alpready looks like this, we could add another dimension. 
```sparql
SELECT ?item {
  {
    ?item wdt:P953 <https://www.saint-ouen.fr/>.
  } UNION {
    ?item wdt:P973 <https://www.saint-ouen.fr/>.
  } UNION {
    ?item wdt:P856 <https://www.saint-ouen.fr/>.
  } UNION {
    ?item wdt:P2699 <https://www.saint-ouen.fr/>.
  } UNION {
    ?item wdt:P953 <https://www.saint-ouen.fr>.
  } UNION {
    ?item wdt:P973 <https://www.saint-ouen.fr>.
  } UNION {
    ?item wdt:P856 <https://www.saint-ouen.fr>.
  } UNION {
    ?item wdt:P2699 <https://www.saint-ouen.fr>.
  }
}
```
don't know if it is possible to have wildcards in urls though

**Comment by derenrich** [comment]
I just ran into this when playing with the extension. https://www.hansonrobotics.com/ should resolve to https://www.wikidata.org/wiki/Q48999902 

I think you can make this work without using SPARQL maybe with wbsearchentities which will more flexibly match

**Comment by fuddl** [comment]
> I just ran into this when playing with the extension. https://www.hansonrobotics.com/ should resolve to https://www.wikidata.org/wiki/Q48999902

right now it does. One issue is that the extension doesn't remember [the edit](https://www.wikidata.org/w/index.php?title=Q48999902&type=revision&diff=1740740726&oldid=1740738448) it made right away. The resolver only kicks in when the Sparql api gives the correct answer. This should be easy to fix thougt.

> I think you can make this work without using SPARQL maybe with wbsearchentities which will more flexibly match

Can you show me an example how to do that? Or is it documented somewhere?

**Comment by derenrich** [comment]
Yeah I figured there was a caching issue with that edit but it should've worked before the edit by fuzzy matching on https (as you described above).

API docs are at https://www.wikidata.org/w/api.php?action=help&modules=wbsearchentities

**Comment by fuddl** [comment]
Ill try to fix the cache first

**Comment by fuddl** [comment]
in version `.273` the resolver should be a little more reliable.

@teolemon @derenrich You can try this by adding 'official website' or 'described by url' to an existing item and then reload or change tabs. The extension should now be able to find the previously connected item instantly. I also fixed a scenario where the website does not end on a `/`. 

Ill close this ticket now, since unfortunatly it is not very well defined. Feel free to open a new one if issues occour 🙏. Please try to describe what behaviour you expect and what is happening instead. The url resolver is whacky by nature, a url is not an id 😭
