### ISSUE TITLE
Allow us to select the language of the website 

### ISSUE THREAD

**Issue by thibaultmol** [fuddl/wd#91]
For ex if you select 'Described at url' it will often show a constraint on wikidata that the language of the site wasn't put in. You might be able to detect the language of the website. or you could give us a dropdown menu in the interface to select it

**Comment by fuddl** [comment]
Please try version `.247` on firefox. The extenson now save the _language of work or name (P407)_ property as a qualifier for all external id or url statements **if** the website carries a valud `lang` attribute.

**Comment by fuddl** [comment]
works for me. reopen this ticket if not for you 😀
