### ISSUE TITLE
Unlogged status & Interaction with Multi-Account Container

### ISSUE THREAD

**Issue by JeanFred** [fuddl/wd#93]
Hello,

When using this extension, it always claims that “It appears that you are not logged into a wikidata account.”.

I believe this is due to me using [Multi-Account Containers](https://github.com/mozilla/multi-account-containers) (I have similar issues with the Wwwyzzerdd extension). (Interestingly, it happens even on tabs that are in my Wikimedia container).

I believe this issue is relevant: https://github.com/mozilla/multi-account-containers/issues/1121

(Filing this for visibility ; to be honest I’m not sure there’s much the developers of the “Wikidata for Web” extension can do :-/)

**Comment by fuddl** [comment]
Thanks, but I'm afraid there is no way for me to address this. The Extension only seems to use the default container for edits.
