### ISSUE TITLE
entry creation doesn't work on FireFox

### ISSUE THREAD

**Issue by mzaki-jp** [fuddl/wd#96]
Entry creation explained in [Creating an entry using Wikidata for Firefox](https://www.wikidata.org/wiki/Wikidata:WikiProject_Journalists/Creating_an_entry_using_Wikidata_for_Firefox) doesn't work on Firefox. On Chrome, it works as anticipated.

I have tried it for Twitter (as explained in the document), Web NDL Authorities (P349), and US Library of Congress (P244).
On Chrome, the barcode icon on the navigation bar turns to pale colors, but it keeps gray on Firefox.

Firefox: 105.0.3 (64bit) on Windows 10
Chrome: 106.0.5249.119 (64bit) on Windows 10

**Comment by fuddl** [comment]
Which version of the extension do you have?

**Comment by mzaki-jp** [comment]
0.275

**Comment by fuddl** [comment]
Would it be possible for you to share your screen with me? 

If you please contact me here for an appointment:
knurled_00_gluon@icloud.com

**Comment by mzaki-jp** [comment]
It is not reproduced in another environment sharing the same Firefox profile
(addon version 0.276, Firefox 105.0.3 (64bit) on Windows 10),
so probably this issue is very specific to my current environment.
I have tried to figure out the factor affecting this by disabling other addons, softwares, etc.,
but no crues in this moment. 

I'd like to close this issue, and will open again if I have any crue to reproduce this problem.
