### ISSUE TITLE
More URL default properties

### ISSUE THREAD

**Issue by slweeb** [fuddl/wd#98]
Currently there are 5 default options when nothing is found on a webpage: full work available at URL, described at URL, official website, URL, and official blog

There are some more that would be useful:

- [P9214](https://www.wikidata.org/wiki/Property:P9214) (FAQ URL)
- [P2078](https://www.wikidata.org/wiki/Property:P2078) (user manual URL)
- [P4945](https://www.wikidata.org/wiki/Property:P4945) (download link)
- [P10027](https://www.wikidata.org/wiki/Property:P10027) (official forum URL)
- [P10311](https://www.wikidata.org/wiki/Property:P10311) (official jobs URL)
- [P10225](https://www.wikidata.org/wiki/Property:P10225) (official shop URL)
- [P7101](https://www.wikidata.org/wiki/Property:P7101) (privacy policy URL)
- [P7014](https://www.wikidata.org/wiki/Property:P7014) (terms of service URL)
- [P9138](https://www.wikidata.org/wiki/Property:P9138) (service status information URL)

There are even more ones that could potentially be added: https://www.wikidata.org/wiki/Wikidata:WikiProject_Websites/Property_autolist

Those are the most important, though.

**Comment by fuddl** [comment]
I could also query **all** existing url properties of offer them to the user. this way it would update without my intervention.

**Comment by slweeb** [comment]
That would be nice, I just didn't know if it would be too unwieldy.

**Comment by fuddl** [comment]
[lets have a look](https://w.wiki/5qen)

**Comment by fuddl** [comment]
lets quite a lot. also very unhelpfully specific. what do the properties we like have in common?

**Comment by slweeb** [comment]
the ones we like shouldn't have a URL match pattern, so things like [P7294](https://www.wikidata.org/wiki/Property:P7294) would be excluded. this might bring it down a lot

**Comment by fuddl** [comment]
[that removes 8](https://w.wiki/5qer)

**Comment by slweeb** [comment]
it might help to also add a filter for P5008 Q15831464 (on focus list of WikiProject Websites), i recently added these statements to properties like these

**Comment by fuddl** [comment]
[this an also removing links that should point to images](https://w.wiki/5qey) (since the extension should execute on images)

**Comment by fuddl** [comment]
[also removing sandbox properties](https://w.wiki/5qe$)

**Comment by slweeb** [comment]
[this one works really well](https://w.wiki/5qf3)

**Comment by fuddl** [comment]
looks smart but [P2699](http://www.wikidata.org/entity/P2699) is missing

**Comment by slweeb** [comment]
[P2699](http://www.wikidata.org/entity/P2699) was missing [Wikidata property related to websites](https://www.wikidata.org/wiki/Q84764641), it shows up now

**Comment by fuddl** [comment]
lets add an order. I'd like the property most likely to be used  at the top. Can we get the list ordered by the number of statements?

**Comment by slweeb** [comment]
i'm not really good at queries so i'm not sure how, we could probably ask at [WD:Request a query](https://www.wikidata.org/wiki/Wikidata:Request_a_query) to modify it

**Comment by fuddl** [comment]
[again removing the one with a match pattern](https://w.wiki/5qf9)

**Comment by slweeb** [comment]
i'll do it right now, they're pretty quick

**Comment by slweeb** [comment]
https://www.wikidata.org/wiki/Wikidata:Request_a_query#Sort_properties_in_query_by_amount_of_uses

**Comment by slweeb** [comment]
hm yeah for sure, perhaps sorting by the ID could be similar?

**Comment by fuddl** [comment]
Might be the cheper way to get almost the same result. I need [another question answered](https://www.wikidata.org/w/index.php?title=Wikidata:Request_a_query&oldid=1755070323#a_specific_url_but_property_agnostic)

**Comment by slweeb** [comment]
they're quite fast huh

**Comment by fuddl** [comment]
So, the final query run for every website not found by a different resolver before could look like this:

```sparql
SELECT ?item ?property WHERE {
	{
		?item ?predicate <https://www.wikidata.org/wiki/Wikidata:Main_Page>.
	} UNION {
		?item ?predicate <https://www.wikidata.org/wiki/Wikidata:Main_Page/>.
	} UNION {
		?item ?predicate <http://www.wikidata.org/wiki/Wikidata:Main_Page>.
	} UNION {
		?item ?predicate <http://www.wikidata.org/wiki/Wikidata:Main_Page/>.
	} UNION {
		?item ?predicate <http://wikidata.org/wiki/Wikidata:Main_Page>.
	} UNION {
		?item ?predicate <http://wikidata.org/wiki/Wikidata:Main_Page/>.
	}
	?property wikibase:directClaim ?predicate.
	FILTER(?property IN (wd:P856, wd:P963, wd:P973, wd:P1065, wd:P1401, wd:P1581, wd:P1896, wd:P2078, wd:P2699, wd:P4238, wd:P4945, wd:P5282, wd:P6269, wd:P6378, wd:P6818, wd:P7014, wd:P7101, wd:P8214, wd:P8768, wd:P8934, wd:P9138, wd:P9214, wd:P9361, wd:P9494, wd:P9601, wd:P9732, wd:P9771, wd:P9904, wd:P10027, wd:P10214, wd:P10225, wd:P10311))
}
LIMIT 1
```
I hope it is a good idea 😅😬

**Comment by fuddl** [comment]
@slweeb please try version `.279`

**Comment by slweeb** [comment]
sorry for the delay! it doesn't look like that version is out on the chrome webstore?

**Comment by fuddl** [comment]
There usually is some delay

**Comment by fuddl** [comment]
should be public now

**Comment by slweeb** [comment]
there seems to be some weird behavior when opening the dropdown menu, looks like its loading more items and refreshing. it works though!

**Comment by fuddl** [comment]
This is indeed a known problem with all dropdowns  in chrome
