### ISSUE TITLE
Dropdowns flicker in chrome

### ISSUE THREAD

**Issue by fuddl** [fuddl/wd#99]
From #98

**Comment by slweeb** [comment]
This makes it pretty unusable really, it would be great if it could just cache it, I was excited to use this feature but this takes forever.

**Comment by slweeb** [comment]
I didn't think about using a custom dropdown. Even so, if the options have to be queried for every single page, it will still take a while. Caching for like a day or an hour would be perfectly fine with the default dropdown.

**Comment by fuddl** [comment]
technically I should already use the http cache in this context.

Chome's fade animation seems to cause the slowdown since in firefox, the select is completly loaded in a fraction of the time without animation

**Comment by fuddl** [comment]
in the current version it should only flicker once or each property that the browser has never seen (and therefore cached) before. I think that makes this bug bearable. I think the issue should be posted to [the chromium bug tracker](https://bugs.chromium.org/).

**Comment by fuddl** [comment]
[bug filed](https://bugs.chromium.org/p/chromium/issues/detail?id=1400070)
